import type { BuildSearchLearningSectionPropsParams } from './types';

export function buildSearchLearningCoreDataProps({
    data,
    selectedSource,
    model,
}: Pick<BuildSearchLearningSectionPropsParams, 'data' | 'selectedSource' | 'model'>) {
    const {
        summary,
        searchLearningEntries,
        searchLearningSummary,
        searchLearningActivityEvents,
        searchLearningActivityStorage,
        searchLearningWorkbench,
        selectedSummary,
        drilldown,
        trendPoints,
        recentSnapshots,
        lowFitQueries,
        recentInteractions,
    } = model;
    const {
        searchLearningTerminalWorkflow,
        searchLearningTerminalAlerts,
        searchLearningTerminalHealth,
        searchLearningTerminalChecklist,
        searchLearningTerminalRunbook,
        searchLearningTerminalMetrics,
        searchLearningTerminalTrends,
        searchLearningTerminalWatchlist,
        searchLearningTerminalMetricsMaxDailyTotal,
        searchLearningTerminalCoverage,
        searchLearningTerminalPriorities,
        searchLearningTerminalOverview,
        searchLearningTerminalHandoff,
        searchLearningTerminalValidation,
        searchLearningRewriteSourceOps,
        searchLearningRewriteSourceOpsSummary,
        searchLearningRewriteSourceActionDrafts,
        searchLearningRewriteSourceActionDraftSummary,
        searchLearningRewriteSourceActionReviewQueue,
        searchLearningRewriteSourceActionReviewSummary,
        searchLearningRewriteSourceApprovalQueue,
        searchLearningRewriteSourceApprovalQueueSummary,
        searchLearningRewriteSourceApprovalActivity,
        searchLearningRewriteSourceApprovalActivitySummary,
        searchLearningActivitySummary,
        searchLearningActivityRecommendations,
        searchLearningActivityOpsQueue,
        searchLearningActivityFollowups,
        searchLearningDraftEntries,
    } = searchLearningWorkbench;

    return {
        coverageDataProps: {
            coverage: data?.searchQualityCoverage,
            searchLearningRewriteSourceOps,
            searchLearningRewriteSourceOpsSummary,
            searchLearningRewriteSourceActionDrafts,
            searchLearningRewriteSourceActionDraftSummary,
            searchLearningRewriteSourceActionReviewQueue,
            searchLearningRewriteSourceActionReviewSummary,
            searchLearningRewriteSourceApprovalQueue,
            searchLearningRewriteSourceApprovalQueueSummary,
            searchLearningRewriteSourceApprovalActivity,
            searchLearningRewriteSourceApprovalActivitySummary,
        },
        terminalDataProps: {
            searchLearningTerminalWorkflow,
            searchLearningTerminalAlerts,
            searchLearningTerminalHealth,
            searchLearningTerminalChecklist,
            searchLearningTerminalRunbook,
            searchLearningTerminalMetrics,
            searchLearningTerminalTrends,
            searchLearningTerminalWatchlist,
            searchLearningTerminalMetricsMaxDailyTotal,
            searchLearningTerminalCoverage,
            searchLearningTerminalPriorities,
            searchLearningTerminalOverview,
            searchLearningTerminalHandoff,
            searchLearningTerminalValidation,
        },
        activityDataProps: {
            searchLearningActivity: searchLearningActivityEvents,
            searchLearningActivitySummary,
            searchLearningActivityRecommendations,
            searchLearningActivityOpsQueue,
            searchLearningActivityFollowups,
            storageLabel: searchLearningActivityStorage,
        },
        queueDataProps: {
            searchLearningDraftEntries,
            searchLearningEntries,
            searchLearningSummary,
        },
        sourceDataProps: {
            lowFitQueries,
            interactionSummary: data?.interactionSummary,
            recentInteractions,
            sources: summary?.sources || [],
            selectedSource,
            selectedSummary,
            drilldown,
            trendPoints,
            recentSnapshots,
        },
    };
}
