import type { BuildSearchLearningSectionPropsParams } from './types';

export function buildSearchLearningChainDataProps({
    model,
}: Pick<BuildSearchLearningSectionPropsParams, 'model'>) {
    const { searchLearningWorkbench } = model;
    const {
        searchLearningOpsCenter,
        searchLearningOpsPlaybooks,
        searchLearningOpsPlaybookActivity,
        searchLearningOpsPlaybookOutcomes,
        searchLearningOpsPlaybookRecommendations,
        searchLearningOpsPlaybookRecommendationQueue,
        searchLearningOpsPlaybookRecommendationActivity,
        searchLearningOpsPlaybookRecommendationOutcomes,
        searchLearningOpsPlaybookRecommendationOutcomeRecommendations,
        searchLearningOpsPlaybookRecommendationOutcomeRecommendationQueue,
        searchLearningOpsPlaybookRecommendationOutcomeRecommendationActivity,
        searchLearningOpsPlaybookRecommendationOutcomeRecommendationOutcomes,
        searchLearningOpsPlaybookRecommendationOutcomeRecommendationOutcomeRecommendations,
        searchLearningOpsPlaybookRecommendationOutcomeRecommendationOutcomeRecommendationQueue,
        searchLearningOpsPlaybookRecommendationOutcomeRecommendationOutcomeRecommendationActivity,
        searchLearningOpsPlaybookRecommendationOutcomeRecommendationOutcomeRecommendationOutcomes,
        searchLearningOpsPlaybookRecommendationOutcomeRecommendationOutcomeRecommendationRecommendations,
        searchLearningOpsCompletionSummary,
        searchLearningOpsCompletionActions,
        searchLearningOpsCompletionActivity,
        searchLearningOpsCompletionOutcomes,
        searchLearningOpsCompletionRecommendations,
        searchLearningOpsCompletionRecommendationQueue,
        searchLearningOpsCompletionRecommendationActivity,
        searchLearningOpsCompletionRecommendationOutcomes,
        searchLearningOpsCompletionRecommendationOutcomeRecommendations,
        searchLearningOpsCompletionRecommendationOutcomeRecommendationQueue,
        searchLearningOpsCompletionRecommendationOutcomeRecommendationActivity,
        searchLearningOpsCompletionRecommendationOutcomeRecommendationOutcomes,
        searchLearningOpsCompletionRecommendationOutcomeRecommendationOutcomeRecommendations,
        searchLearningOpsCompletionRecommendationOutcomeRecommendationOutcomeRecommendationQueue,
        searchLearningOpsCompletionRecommendationOutcomeRecommendationOutcomeRecommendationActivity,
        searchLearningOpsCompletionRecommendationOutcomeRecommendationOutcomeRecommendationOutcomes,
        searchLearningOpsCompletionRecommendationOutcomeRecommendationOutcomeRecommendationRecommendations,
        searchLearningOpsCompletionRecommendationOutcomeRecommendationOutcomeRecommendationRecommendationQueue,
        searchLearningOpsCompletionRecommendationOutcomeRecommendationOutcomeRecommendationRecommendationActivity,
        searchLearningOpsCompletionRecommendationOutcomeRecommendationOutcomeRecommendationRecommendationOutcomes,
        searchLearningOpsCompletionRecommendationOutcomeRecommendationOutcomeRecommendationRecommendationRecommendations,
        searchLearningOpsCompletionQueue,
        searchLearningImpactSummary,
        searchLearningImpactClusterRollup,
        searchLearningImpactClusters,
        searchLearningRewritePacks,
        searchLearningRewriteRecommendations,
        searchLearningRewriteRecommendationSummary,
        searchLearningRewriteSourceDrafts,
        searchLearningRewriteSourceDraftSummary,
    } = searchLearningWorkbench;

    return {
        playbookChainDataProps: {
            searchLearningOpsPlaybookRecommendationOutcomeRecommendationOutcomeRecommendations,
            searchLearningOpsPlaybookRecommendationOutcomeRecommendationOutcomeRecommendationActivity,
            searchLearningOpsPlaybookRecommendationOutcomeRecommendationOutcomeRecommendationOutcomes,
            searchLearningOpsPlaybookRecommendationOutcomeRecommendationOutcomeRecommendationRecommendations,
            searchLearningOpsPlaybookRecommendationOutcomeRecommendationOutcomeRecommendationQueue,
            searchLearningOpsPlaybookRecommendationActivity,
            searchLearningOpsPlaybookRecommendations,
            searchLearningOpsPlaybookRecommendationOutcomes,
            searchLearningOpsPlaybookRecommendationOutcomeRecommendations,
            searchLearningOpsPlaybookRecommendationOutcomeRecommendationQueue,
            searchLearningOpsPlaybookRecommendationOutcomeRecommendationActivity,
            searchLearningOpsPlaybookRecommendationOutcomeRecommendationOutcomes,
            searchLearningImpactSummary,
            searchLearningImpactClusterRollup,
            searchLearningImpactClusters,
            searchLearningRewritePacks,
            searchLearningRewriteRecommendationSummary,
            searchLearningRewriteRecommendations,
            searchLearningRewriteSourceDraftSummary,
            searchLearningRewriteSourceDrafts,
        },
        completionChainDataProps: {
            searchLearningOpsCompletionSummary,
            searchLearningOpsCompletionActions,
            searchLearningOpsCompletionQueue,
            searchLearningOpsPlaybookRecommendationOutcomeRecommendationOutcomeRecommendationRecommendations,
            searchLearningOpsCompletionActivity,
            searchLearningOpsCompletionOutcomes,
            searchLearningOpsCompletionRecommendations,
            searchLearningOpsCompletionRecommendationQueue,
            searchLearningOpsCompletionRecommendationActivity,
            searchLearningOpsCompletionRecommendationOutcomes,
            searchLearningOpsCompletionRecommendationOutcomeRecommendations,
            searchLearningOpsCompletionRecommendationOutcomeRecommendationQueue,
            searchLearningOpsCompletionRecommendationOutcomeRecommendationActivity,
            searchLearningOpsCompletionRecommendationOutcomeRecommendationOutcomes,
            searchLearningOpsCompletionRecommendationOutcomeRecommendationOutcomeRecommendations,
            searchLearningOpsCompletionRecommendationOutcomeRecommendationOutcomeRecommendationQueue,
            searchLearningOpsCompletionRecommendationOutcomeRecommendationOutcomeRecommendationActivity,
            searchLearningOpsCompletionRecommendationOutcomeRecommendationOutcomeRecommendationOutcomes,
            searchLearningOpsCompletionRecommendationOutcomeRecommendationOutcomeRecommendationRecommendations,
            searchLearningOpsCompletionRecommendationOutcomeRecommendationOutcomeRecommendationRecommendationQueue,
            searchLearningOpsCompletionRecommendationOutcomeRecommendationOutcomeRecommendationRecommendationActivity,
            searchLearningOpsCompletionRecommendationOutcomeRecommendationOutcomeRecommendationRecommendationOutcomes,
            searchLearningOpsCompletionRecommendationOutcomeRecommendationOutcomeRecommendationRecommendationRecommendations,
        },
        playbookDataProps: {
            searchLearningOpsPlaybooks,
            searchLearningOpsPlaybookActivity,
            searchLearningOpsPlaybookOutcomes,
            searchLearningOpsPlaybookRecommendations,
            searchLearningOpsPlaybookRecommendationQueue,
            searchLearningOpsCenter,
        },
    };
}
